<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>소스코드 - 프로</title>
  <link rel="stylesheet" href="<?=$basePath?>node_modules/bootstrap/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
<body>
  <nav class="navbar navbar-expand navbar-dark bg-dark">
    <div class="container">
      <a href="<?=$basePath?>" class="navbar-brand">소스코드</a>

      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a href="<?=$router->pathFor('source.search')?>" class="nav-link">
            검색
          </a>
        </li>
      </ul>

      <form class="form-inline" action="<?=$router->pathFor('logout')?>" method="post">
        <button type="submit" class="btn btn-link text-muted" title="로그아웃"><i class="fas fa-sign-out-alt"></i></button>
      </form>
    </div>
  </nav>

  <div class="container">
    <div class="table-responsive">
    <table class="table" style="white-space: nowrap">
    <thead>
      <tr>
        <th>#</th>
        <th>제출한 사람</th>
        <th>과제</th>
        <th>채점 결과</th>
        <th>길이</th>
        <th>제출한 시간</th>
      </tr>
    </thead>
    <tbody>
<?php foreach ($sources as $source): ?>
      <tr>
        <td><?=$source['source_id']?></td>
        <td>
          <a href="?user_id=<?=$source['uid']?>">
            <?=$source['gen']?>기 <?=$source['name']?>
          </a>
        </td>
        <td>
          <a href="?task_id=<?=$source['tid']?>" title="<?=htmlentities($source['title'])?>">
            <?=$source['tid']?>
          </a><small>
            <a href="<?=$router->pathFor('task.show', ['task_id' => $source['tid']])?>">
              <i class="fas fa-external-link-alt"></i>
            </a>
          </small>
        </td>
        <td><?=['정답','컴파일 에러','런타임 에러',$source['score'] . '점'][$source['status']]?></td>
        <td>
          <a href="<?=$router->pathFor('source.show', ['source_id' => $source['source_id']])?>">
            <?=$source['size']?>B
          </a>
        </td>
        <td><?=$source['date']?></td>
      </tr>
<?php endforeach; ?>
    </tbody>
    </table>
    </div>

    <nav>
      <ul class="pagination justify-content-end">
        <li class="page-item">
          <a class="page-link" href="<?=$nextUrl?>">다음 페이지</a>
        </li>
      </ul>
    </nav>
  </div>

</html>
