<?php
header('Content-Type: text/plain; charset=UTF-8');

//$SOURCES = __DIR__ . '/_data/sources/';

$file = $config->get('storage.sources') . '/' . implode('_', [ $source['tid'], $source['uid'], $source['fid'] ]) . '.c';

if (stripos(realpath($file), realpath($config->get('storage.sources'))) !== 0)
{
    exit;
}

$fp = fopen($file, 'rb');
if ($fp === false)
{
    exit;
}
fseek($fp, 3);

while (!feof($fp))
{
    echo fread($fp, 4096);
    flush();
}
fclose($fp);
