<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>과제 - 프로</title>
  <link rel="stylesheet" href="/node_modules/bootstrap/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
<body>
  <nav class="navbar navbar-expand navbar-dark bg-dark">
    <div class="container">
      <span class="navbar-brand">과제</span>

      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a href="<?=$router->pathFor('task.index')?>" class="nav-link">
            진행 중
          </a>
        </li>
        <li class="nav-item active">
          <a href="<?=$router->pathFor('task.list')?>" class="nav-link">
            아카이브
          </a>
        </li>
        <li class="nav-item">
          <a href="<?=$router->pathFor('task.new')?>" class="nav-link">
            게시
          </a>
        </li>
      </ul>

      <form class="form-inline" action="<?=$router->pathFor('logout')?>" method="post">
        <button type="submit" class="btn btn-link text-muted" title="로그아웃"><i class="fas fa-sign-out-alt"></i></button>
      </form>
    </div>
  </nav>

  <div class="container">
    <ul class="nav nav-pills justify-content-center">
<?php for ($i = 2015; $i <= date('Y'); $i++): ?>
      <li class="nav-item">
        <a href="<?=$router->pathFor('task.list', [
          'year' => $i,
        ])?>"
  <?php if ($i == $displayYear): ?>
            class="nav-link active"
  <?php else: ?>
            class="nav-link"
  <?php endif; ?>
        >
          <?=$i?>
        </a>
      </li>
<?php endfor;?>
    </ul>
<?php if ($shouldDisplayMonthFilter): ?>
    <ul class="nav nav-pills justify-content-center">
  <?php for ($i = 1; $i <= 12; $i++): ?>
      <li class="nav-item">
        <a href="<?=$router->pathFor('task.list', [
          'year' => $displayYear,
          'month' => $i,
        ])?>"
    <?php if ($i == $displayMonth): ?>
            class="nav-link active"
    <?php else: ?>
            class="nav-link"
    <?php endif; ?>
        >
          <?=$i?>
        </a>
      </li>
  <?php endfor;?>
    </ul>
<?php endif;?>


    <div class="list-group">
<?php foreach ($tasks as $key => $task): ?>
      <a class="list-group-item list-group-item-action"
          href="<?=$router->pathFor('task.show', ['task_id' => $task['idx']])?>">
        <h5 class="mb-1"><?=htmlspecialchars($task['title'])?></h5>
        <div class="mb-0">
          <i class="fas fa-calendar-alt" title="게시일"></i> <?=$task['date']?>
          <i class="fas fa-calendar-check" title="마감일"></i> <?=$task['date']?>
        </div>
      </a>
<?php endforeach; ?>
    </div>
  </div>

</html>
