<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>과제 - 프로</title>
  <link rel="stylesheet" href="<?=$basePath?>node_modules/bootstrap/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
  <style>
    label {
      display: block;
    }
  </style>
<body>
  <nav class="navbar navbar-expand navbar-dark bg-dark">
    <div class="container">
      <a href="<?=$basePath?>" class="navbar-brand">과제</a>

      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a href="<?=$router->pathFor('task.index')?>" class="nav-link">
            진행 중
          </a>
        </li>
        <li class="nav-item">
          <a href="<?=$router->pathFor('task.list')?>" class="nav-link">
            아카이브
          </a>
        </li>
        <li class="nav-item active">
          <a href="<?=$router->pathFor('task.new')?>" class="nav-link">
            게시
          </a>
        </li>
      </ul>

      <form class="form-inline" action="<?=$router->pathFor('logout')?>" method="post">
        <button type="submit" class="btn btn-link text-muted" title="로그아웃"><i class="fas fa-sign-out-alt"></i></button>
      </form>
    </div>
  </nav>

  <div class="container">
    <form action="<?=$router->pathFor('task.store')?>" method="post">
      <div class="form-group">
        <label>시작: <input name="start" class="form-control" type="text" placeholder="2015-04-13" pattern="\d{4}-\d{2}-\d{2}" required></label>
      </div>
      <div class="form-group">
        <label>종료: <input name="end" class="form-control" type="text" placeholder="2015-04-13" pattern="\d{4}-\d{2}-\d{2}" required></label>
      </div>
      <div class="form-group">
        <label class="mb-0">제목: <input name="title" class="form-control" required></label>
      </div>
      <div class="form-group">
        <label class="mb-0" for="content"><span class="float-left">내용: </span><textarea name="content" class="form-control markdown-edit" rows="10"></textarea></label>
        <button class="span btn btn-block btn-secondary" type="button">늘이기</button>
      </div>
      <div class="form-row">
        <div class="col-sm">
          <div class="form-group">
            <label>
              예시 입력:
              <textarea name="in" class="form-control text-light bg-dark" rows="6" wrap="off"></textarea>
            </label>
          </div>
        </div>
        <div class="col-sm">
          <div class="form-group">
            <label>
              예시 출력:
              <textarea name="out" class="form-control text-light bg-dark" rows="6" wrap="off"></textarea>
            </label>
          </div>
        </div>
      </div>

      <h2>
        <button type="button" class="add-test btn btn-secondary float-right">
          추가
        </button>
        채점 데이터
      </h2>
      <div id="tests" class="list-group list-group-flush">
      </div>
      <div class="form-group">
        <button type="submit" class="btn btn-primary btn-block">저장하기</button>
      </div>
    </form>
  </div>

  <script src="<?=$basePath?>node_modules/jquery/dist/jquery.min.js"></script>
  <script src="<?=$basePath?>_data/markdown-edit.js"></script>
  <script>
    $('.span').on('click', function(e) {
      e.preventDefault();
      var target = $('textarea', $(this).prev());
      target.height(target.height() + 150);
    });
    $('[name=start]').on('input propertychange', function() {
      $('[name=end]').val($(this).val());
    });
    $('form').on('submit', function(e) {
      if (!confirm('과제를 제대로 입력했나요?'))
      {
        e.preventDefault();
        return;
      }
      $('#tests').find(':first[hidden]').remove();
    });
    $('.add-test').on('click', function (e) {
      e.preventDefault();
      $('#tests').append(`
        <div class="list-group-item">
          <button type="button" class="delete-test btn btn-secondary float-right">
            삭제
          </button>
          <label>
            최종 점수:
            <input name="test_score[]" type="number" class="form-control" required>
          </label>

          <div class="form-row">
            <div class="col-sm">
              <div class="form-group">
                <label>
                  입력:
                  <textarea name="test_input[]" class="form-control text-light bg-dark" rows="6" wrap="off"></textarea>
                </label>
              </div>
            </div>
            <div class="col-sm">
              <div class="form-group">
                <label>
                  출력:
                  <textarea name="test_output[]" class="form-control text-light bg-dark" rows="6" wrap="off"></textarea>
                </label>
              </div>
            </div>
          </div>
        </div>
      `);
    });
    $(document).on('click', '.delete-test', function (e) {
      e.preventDefault();
      $(this).parent().remove();
    });
  </script>
</html>
