<?php

$C_BASE = <<<EOP
#include &lt;stdio.h&gt;

int main()
{
    return 0;
}

EOP;

?><!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>과제 - 프로</title>
  <link rel="stylesheet" href="<?=$basePath?>node_modules/bootstrap/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
  <link rel="stylesheet" href="<?=$basePath?>node_modules/codemirror/lib/codemirror.css">
  <link rel="stylesheet" href="<?=$basePath?>node_modules/codemirror/theme/mdn-like.css">
  <style>
    .console {
      line-height: 1.14;
      padding: .5rem;
      overflow-x: auto;
    }
    .CodeMirror {
      font-family: SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace;
      font-size: 1rem;
      height: auto;
    }
  </style>
<body>
  <nav class="navbar navbar-expand navbar-dark bg-dark">
    <div class="container">
      <a href="<?=$basePath?>" class="navbar-brand">과제</a>

      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a href="<?=$router->pathFor('task.index')?>" class="nav-link">
            진행 중
          </a>
        </li>
        <li class="nav-item active">
          <a href="<?=$router->pathFor('task.list')?>" class="nav-link">
            아카이브
          </a>
        </li>
        <li class="nav-item">
          <a href="<?=$router->pathFor('task.new')?>" class="nav-link">
            게시
          </a>
        </li>
      </ul>

      <form class="form-inline" action="<?=$router->pathFor('logout')?>" method="post">
        <button type="submit" class="btn btn-link text-muted" title="로그아웃"><i class="fas fa-sign-out-alt"></i></button>
      </form>
    </div>
  </nav>

  <div class="container">
    <h2 class="mb-1"><?=htmlspecialchars($task['title'])?></h2>
    <div class="mb-3">
      <i class="fas fa-calendar-alt" title="게시일"></i> <time><?=$task['start']?></time>
      <i class="fas fa-calendar-check" title="마감일"></i> <?=$task['end']?>
    </div>

    <div class="mb-3" style="text-align: justify"><?=(new Parsedown())->text($task['content'])?></div>

    <aside class="row">
      <div class="col-sm">
        <h4>예시 입력</h4>
        <pre class="console text-light bg-dark"><?=htmlspecialchars($task['in'])?></pre>
      </div>
      <div class="col-sm">
        <h4>예시 출력</h4>
        <pre class="console text-light bg-dark"><?=htmlspecialchars($task['out'])?></pre>
      </div>
    </aside>

    <h2>코드</h2>
    <form id="submit" action="<?=$router->pathFor('source.store', [
      'task_id' => $task['idx'],
    ])?>" method="post">
      <div class="form-group">
        <textarea id="source" name="source" class="form-control" wrap="off" rows="10"><?=$C_BASE?></textarea>
      </div>
      <div class="form-group">
        <button type="submit" class="btn btn-primary btn-block">제출하기</button>
      </div>
    </form>
  </div>

  <script src="<?=$basePath?>node_modules/codemirror/lib/codemirror.js"></script>
  <script src="<?=$basePath?>node_modules/codemirror/mode/clike/clike.js"></script>
  <script src="<?=$basePath?>node_modules/codemirror/addon/edit/matchbrackets.js"></script>
  <script src="<?=$basePath?>node_modules/codemirror/addon/edit/closebrackets.js"></script>
  <script>
    var code = CodeMirror.fromTextArea(document.getElementById('source'), {
      indentUnit: 4,
      mode: 'text/x-csrc',
      lineNumbers: true,
      viewportMargin: Infinity,
      theme: 'mdn-like',
      matchBrackets: true,
      autoCloseBrackets: true,
    });
    // var saveTimer;
    // $('textarea').on('input propertychange', function(e) {
    //     clearTimeout(saveTimer);
    //     saveTimer = setTimeout(function() {
    //             // localStorage['pro_submit'] = $('textarea').val();
    //             localStorage['pro_submit'] = code.getValue();
    //         }, 1000);
    // });
    // if (localStorage['pro_submit'])
    // {
    //     // $('textarea').val(localStorage['pro_submit']);
    //     code.setValue(localStorage['pro_submit']);
    // }
    document.getElementById('submit').addEventListener('submit', function (e) {
      code.save();
      var sourceEl = document.getElementById('textarea');
      sourceEl.value = sourceEl.value
        .replace(/\u00A0/g, ' ')
        .replace(/\t/g, '    ')
        .replace(/\r\n/g, '\n').replace(/\r/g, '\n');
    });
  </script>
</html>
