<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>활동일지 - 프로</title>
  <link rel="stylesheet" href="/node_modules/bootstrap/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
<body>
  <nav class="navbar navbar-expand navbar-dark bg-dark">
    <div class="container">
      <span class="navbar-brand">활동일지</span>

      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a href="<?=$router->pathFor('activity.list')?>" class="nav-link">
            아카이브
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<?=$router->pathFor('activity.new')?>">작성</a>
        </li>
      </ul>

      <form class="form-inline" action="<?=$router->pathFor('logout')?>" method="post">
        <button type="submit" class="btn btn-link text-muted" title="로그아웃"><i class="fas fa-sign-out-alt"></i></button>
      </form>
    </div>
  </nav>

  <div class="container">
    <ul class="nav nav-pills justify-content-center">
<?php for ($i = 2015; $i <= date('Y'); $i++): ?>
      <li class="nav-item">
        <a href="<?=$router->pathFor('activity.list', [
          'year' => $i,
        ])?>"
  <?php if ($i == $displayYear): ?>
            class="nav-link active"
  <?php else: ?>
            class="nav-link"
  <?php endif; ?>
        >
          <?=$i?>
        </a>
      </li>
<?php endfor;?>
    </ul>
<?php if ($shouldDisplayMonthFilter): ?>
    <ul class="nav nav-pills justify-content-center">
  <?php for ($i = 1; $i <= 12; $i++): ?>
      <li class="nav-item">
        <a href="<?=$router->pathFor('activity.list', [
          'year' => $displayYear,
          'month' => $i,
        ])?>"
    <?php if ($i == $displayMonth): ?>
            class="nav-link active"
    <?php else: ?>
            class="nav-link"
    <?php endif; ?>
        >
          <?=$i?>
        </a>
      </li>
  <?php endfor;?>
    </ul>
<?php endif;?>


    <div class="list-group">
<?php foreach ($activities as $key => $activity): ?>
      <a class="list-group-item list-group-item-action flex-column align-items-start"
          href="<?=$router->pathFor('activity.show', ['activity_id' => $activity['idx']])?>">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-0"><?=htmlspecialchars($activity['purpose'])?></h5>
          <span>
            <i class="fas fa-users"></i> <?=$attendCounts[$key]?>명
            <i class="fas fa-location-arrow"></i> <?=$activity['place']?>
            <i class="fas fa-calendar-alt"></i> <?=(new DateTime($activity['start']))->format('Y-m-d')?>
          </span>
        </div>
      </a>
<?php endforeach; ?>
    </div>
  </div>

</html>
