<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <title>프로 활동일지 작성</title>
    <link rel="stylesheet" href="/node_modules/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/node_modules/codemirror/lib/codemirror.css">
    <link rel="stylesheet" href="/node_modules/tui-editor/dist/tui-editor.min.css">
    <link rel="stylesheet" href="/node_modules/tui-editor/dist/tui-editor-contents.min.css">
    <link rel="stylesheet" href="/node_modules/highlight.js/styles/github.css">
<body>
    <form action="<?=$router->pathFor('activity.store')?>" method="POST" enctype="multipart/form-data">
        <header><span>프로 활동일지 작성</span><button type="submit">&#10004;</button></header>
        <label>모임장소: <input name="place" type="text" placeholder="M502"></label>
        <label>시작: <input name="start" type="text" placeholder="2015-04-13 15:00" pattern="\d{4}-\d{2}-\d{2} \d{2}:\d{2}" required></label>
        <label>종료: <input name="end" type="text" placeholder="2015-04-13 16:00" pattern="\d{4}-\d{2}-\d{2} \d{2}:\d{2}" required></label>
        <ul><li>누르면 지워집니다.</ul><!-- ul > li > input[name=attend[]] -->
        <label>참여 회원: <select><option></option><?php
            foreach ($members as $member)
            {
                echo '<option value="', $member['id'], '">',
                     $member['id'], ' ', $member['gen'], '기 ', $member['name'];
            }
        ?></select></label>
        <label>목적: <textarea name="purpose" rows="1" required></textarea></label><button class="span">늘이기</button>
        <label>내용: <textarea name="content"></textarea></label><button class="span">늘이기</button>
        <label>파일 첨부: <input name="attach[]" type="file" multiple></label>
    </form>
    <div id="sec"></div>
    <script src="/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="/node_modules/popper.js/dist/umd/popper.min.js"></script>
    <script src="/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="/node_modules/codemirror/lib/codemirror.js"></script>
    <script src="/node_modules/tui-editor/dist/tui-editor-Editor-all.min.js"></script>
    <script>
$('#sec').tuiEditor({
    initialEditType: 'markdown',
    previewStyle: 'vertical',
    height: '300px'
});
        $('select').on('change', function(e) {
            e.preventDefault();
            var option = $(this.selectedOptions[0]);
            if (!option.val().length)
            {
                return;
            }
            $(this).val('');
            option.hide().prop('tab-index', -1);

            $('ul').append(
                $('<li>').text(option.text())
                    .append($('<input>', { name: 'attend[]', value: option.val(), type: 'hidden' })));
        });
        $(document).on('click', 'li', function(e) {
            e.preventDefault();
            $('option[value=' + $('input', this).val() + ']').show().removeProp('tab-index');
            $(this).remove();
        });
        $('[name=purpose]').on('keypress', function(e) {
            if (e.keyCode == 13) // ENTER
            {
                e.preventDefault();
            }
        });
        $('.span').on('click', function(e) {
            e.preventDefault();
            var target = $('textarea', $(this).prev());
            target.height(target.height() + 150);
        });
        $('[name=start]').on('input propertychange', function() {
            $('[name=end]').val($(this).val());
        });
        $('form').on('submit', function(e) {
            if (!confirm('활동 정보를 제대로 기입했나요?'))
            {
                e.preventDefault();
                return;
            }
        });
    </script>
</html>
