<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>활동일지 - 프로</title>
  <link rel="stylesheet" href="<?=$router->pathFor()?>node_modules/bootstrap/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
<body>
  <nav class="navbar navbar-expand navbar-dark bg-dark">
    <div class="container">
      <a href="<?=$router->pathFor()?>" class="navbar-brand">활동일지</a>

      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a href="<?=$router->pathFor('activity.list')?>" class="nav-link">
            아카이브
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<?=$router->pathFor('activity.new')?>">작성</a>
        </li>
      </ul>

      <form class="form-inline" action="<?=$router->pathFor('logout')?>" method="post">
        <button type="submit" class="btn btn-link text-muted" title="로그아웃"><i class="fas fa-sign-out-alt"></i></button>
      </form>
    </div>
  </nav>

  <div class="container">
<?php
  $start = strtotime($activity['start']);
  $end = strtotime($activity['end']);
?>
    <h2 class="mb-1"><?=htmlspecialchars($activity['purpose'])?></h5>
    <div class="mb-3">
      <i class="fas fa-users" title="참여 회원 수"></i> <?=count($attends)?>명
      <i class="fas fa-location-arrow" title="활동 장소"></i> <?=$activity['place']?>
      <i class="fas fa-calendar-alt" title="활동 시간"></i> <time><?=date('Y-m-d H:i', $start)?></time> ~ <?=date((date('d', $start) != date('d', $end) ? 'Y-m-d ' : '') . 'H:i', $end)?>
    </div>

    <!-- // TODO: markdown converter로 바꾸기 -->
    <p><?=nl2br(htmlspecialchars($activity['content']))?></p>

    <h5>첨부 파일</h5>
    <ul>
<?php foreach ($attaches as $i): ?>
      <li>
        <a href="<?=$router->pathFor('file.download', [
            'file_id' => $i['md5'],
        ])?>">
            <?=htmlspecialchars($i['name'])?>
        </a>
      </li>
<?php endforeach; ?>
    </ul>

    <h5>참여 회원</h5>
    <ul>
<?php foreach ($attends as $i): ?>
      <li><?=$i['gen']?>기 <?=htmlspecialchars($i['name'])?>
<?php endforeach; ?>
    </ul>
  </div>

</html>
