<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <title>프로 활동일지</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/earlyaccess/notosanskr.css">
    <style>
        body {
            margin: 3em .5em 0 .5em;
            line-height: 1.6;
            font-size: 16px;
            font-family: 'Noto Sans KR', 'Malgun Gothic', sans-serif;
        }
        body > header {
            position: fixed;
            top: 0;
            left: 0;
            background: #efefef;
            border-bottom: 1px solid #ccc;
            line-height: 2.5em;
            width: 100%;
            padding: 0 .5em;
            box-sizing: border-box;
            white-space: nowrap;
            font-weight: bold;
        }
        header a {
            float: right;
            text-decoration: none;
        }
    </style>
<body>
    <header>프로 활동일지 <a href="task.php">과제</a></header>
<?php
    $start = strtotime($activity['start']);
    $end = strtotime($activity['end']);
?>
    <h2><?=htmlspecialchars($activity['purpose'])?></h2>
    @<?=$activity['place']?> #<time><?=date('Y-m-d H:i', $start)?></time> ~ <?=date((date('d', $start) != date('d', $end) ? 'Y-m-d ' : '') . 'H:i', $end)?>

    <p><?=nl2br(htmlspecialchars($activity['content']))?>


    <h3>첨부 파일</h3>
    <ul>
<?php foreach ($attaches as $i): ?>
        <li><a href="<?=$router->pathFor('file.download', [
            'file_id' => $i['md5'],
        ])?>">
            <?=htmlspecialchars($i['name'])?>
        </a>
<?php endforeach; ?>
    </ul>

    <h3>참여 회원</h3>
    <ul>
<?php foreach ($attends as $i): ?>
        <li><?=$i['gen']?>기 <?=htmlspecialchars($i['name'])?>
<?php endforeach; ?>
    </ul>
</html>
